version: 0.1

phases:
  install:
    commands:
      - echo "==> install"
  pre_build:
    commands:
      - echo "==> pre-build"
      - bash config.sh
  build:
    commands:
      - echo "==> build"
  post_build:
    commands:
      - echo "==> post-build"
      - bash publish.sh
