version: 0.1

phases:
  install:
    commands:
      - echo "==> install"
  pre_build:
    commands:
      - echo "==> pre-build"
      - aws s3 cp ${S3} /etc/letsencrypt --recursive
      - |
        if [ `ls -1A /etc/letsencrypt | wc -l` -eq 0 ] ;
        then
          echo "==> register new account"
          certbot register --agree-tos --register-unsafely-without-email
        else
          echo "==> use existing account"
        fi
  build:
    commands:
      - echo "==> build"
      - |
        if [ ! -d "/etc/letsencrypt/archive/${FQDN}" ] ;
        then
          echo "==> request certificates for ${FQDN}"
        else
          echo "==> re-new of ${FQDN}"
        fi
  post_build:
    commands:
      - echo "==> post-build"
      - aws s3 cp /etc/letsencrypt ${S3} --recursive
