version: 0.1

phases:
  install:
    commands:
      - echo "==> install"
  pre_build:
    commands:
      - echo "==> pre-build"
      - aws s3 cp ${S3} /etc/letsencrypt --recursive
      - |
        if [ `ls -1A /etc/letsencrypt | wc -l` -eq 0 ] ;
        then
          certbot register --agree-tos --register-unsafely-without-email
        fi
  build:
    commands:
      - echo "==> build"
      - certbot certonly --staging --dns-route53 -d ${FQDN} --register-unsafely-without-email --agree-tos
  post_build:
    commands:
      - echo "==> post-build"
      - aws s3 cp /etc/letsencrypt ${S3} --recursive
