version: 0.1

phases:
  install:
    commands:
      - echo "==> install"
  pre_build:
    commands:
      - echo "==> pre-build"
      - aws s3 cp ${S3}/letsencrypt.tgz /tmp/letsencrypt.tgz && tar -C / -xvf /tmp/letsencrypt.tgz || echo "empty project"
      - |
        if [ `ls -1A /etc/letsencrypt | wc -l` -eq 0 ] ;
        then
          certbot register --agree-tos -m ${EMAIL}
        fi
  build:
    commands:
      - echo "==> build"
      - |
        if [ ! -d "/etc/letsencrypt/archive/${DOMAIN}" ] ;
        then
          echo "==> request certificates for ${DOMAIN}"
          certbot certonly --dns-route53 -d ${DOMAIN} -m ${EMAIL} --agree-tos --non-interactive
        else
          echo "==> re-new of ${DOMAIN}"
          certbot renew
        fi
  post_build:
    commands:
      - echo "==> post-build"
      - tar -czvf /tmp/letsencrypt.tgz /etc/letsencrypt
      - aws s3 cp /etc/letsencrypt/live/${DOMAIN}/cert.pem ${S3}/${DOMAIN}/cert.pem
      - aws s3 cp /etc/letsencrypt/live/${DOMAIN}/privkey.pem ${S3}/${DOMAIN}/privkey.pem
      - aws s3 cp /tmp/letsencrypt.tgz ${S3}/letsencrypt.tgz
